name: Demo Web API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Nginx
      run: |
        sudo apt-get update
        sudo apt-get install -y nginx
        sudo mv $GITHUB_WORKSPACE/index.html /var/www/html/index.html
        sudo mv $GITHUB_WORKSPACE/openapi.yml /var/www/html/openapi.yml
        sudo systemctl start nginx

    - name: Display Nginx Status
      run: sudo systemctl status nginx

